// Sagas
export const FETCH_HOME_TOP_IMAGE = 'FETCH_HOME_TOP_IMAGE';
export const FETCH_HOME_SCHEDULE_RECENT = 'FETCH_HOME_SCHEDULE_RECENT';
export const FETCH_HOME_SCHEDULE_RECOMMEND = 'FETCH_HOME_SCHEDULE_RECOMMEND';
export const FETCH_HOME_USER_RECOMMEND = 'FETCH_HOME_USER_RECOMMEND';
export const FETCH_HOME_CALENDAR_RECOMMEND = 'FETCH_HOME_CALENDAR_RECOMMEND';
export const FETCH_HOME_CALENDAR_RECENT = 'FETCH_HOME_CALENDAR_RECENT';

// Reducer
export const FETCH_HOME_TOP_IMAGE_SUCCESS = 'FETCH_HOME_TOP_IMAGE_SUCCESS';
export const FETCH_HOME_SCHEDULE_RECENT_SUCCESS = 'FETCH_HOME_SCHEDULE_RECENT_SUCCESS';
export const FETCH_HOME_SCHEDULE_RECOMMEND_SUCCESS = 'FETCH_HOME_SCHEDULE_RECOMMEND_SUCCESS';
export const FETCH_HOME_USER_RECOMMEND_SUCCESS = 'FETCH_HOME_USER_RECOMMEND_SUCCESS';
export const FETCH_HOME_CALENDAR_RECENT_SUCCESS = 'FETCH_HOME_CALENDAR_RECENT_SUCCESS';
export const FETCH_HOME_CALENDAR_RECOMMEND_SUCCESS = 'FETCH_HOME_CALENDAR_RECOMMEND_SUCCESS';
